FROM ubuntu:18.04

MAINTAINER Alban Gaignard <alban.gaignard@univ-nantes.fr>

SHELL ["/bin/bash", "-c"]
WORKDIR /home

# Update Ubuntu + basic install
RUN apt-get update
RUN apt-get install -y git curl wget bzip2 libcurl4-openssl-dev libxml2-dev zlib1g-dev

# Install R
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y libcurl4-gnutls-dev libssl-dev
RUN apt-get install -y libcurl4-openssl-dev libssl-dev
RUN apt-get install -y r-base r-base-dev
RUN Rscript -e "install.packages('devtools')"
RUN Rscript -e "devtools::install_github('IRkernel/IRkernel')"

# Install R Jupyter Kernel
#RUN echo 'install.packages(c("repr", "IRdisplay", "crayon", "pbdZMQ", "devtools"),repos="http://cran.us.r-project.org", dependencies=TRUE)' > /tmp/packages.R && Rscript /tmp/packages.R
#RUN echo 'devtools::install_github("IRkernel/IRkernel")' > /tmp/packages.R && Rscript /tmp/packages.R

# Install R kernel
#RUN echo 'IRkernel::installspec()' > /tmp/temp.R && Rscript /tmp/temp.R

# Install miniconda to /miniconda
RUN curl -LO https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
RUN bash Miniconda3-latest-Linux-x86_64.sh -p /my-miniconda -b
RUN rm Miniconda3-latest-Linux-x86_64.sh
ENV PATH=/my-miniconda/bin:${PATH}
RUN conda config --add channels conda-forge
RUN conda config --add channels bioconda
COPY binder/environment.yml .
RUN conda env create -n ican-ml --file environment.yml


# RUN Rscript -e "IRkernel::installspec()"


COPY notebooks notebooks
COPY data data

# Copy repository files to the image
#COPY README.md .
#COPY bravo bravo
#COPY tests tests
#COPY pyBravo.py .
#COPY BRAvo-python-API-tutorial.ipynb .

#CMD [ "bash" ]
CMD /bin/bash -c 'source activate ican-ml && jupyter notebook --ip 0.0.0.0 --no-browser --allow-root'
#CMD /bin/bash -c 'source activate pybravo && cd python && nosetests'

#CMD /bin/bash -c 'jupyter notebook --ip 0.0.0.0 --no-browser --allow-root'
