name: ICAN-experiments

dependencies:
        - python>=3.6
        - pandas
        - jupyter
        - scikit-learn
        - matplotlib
        - missingno
        - scipy
        - rpy2
        - R
