dependencies:
  - pandas
  - jupyter
  - matplotlib
  - scipy
  - r-base=3.6.3
  - r-devtools=2.2*
  - r-irkernel=1.1*
  - r-randomforest=4.6*
  - r-rcurl=1.98*
  - r-factominer
  - r-tidyverse
  - r-viridis
  - r-factoextra
  - r-plot3D
  - r-ggplot2
  - r-rocr
  - r-pls
